#! /bin/bash

# Config variable, modify to your needs
EMAIL_TO='recipient@email.com'
EMAIL_FROM='sender@email.com'
EMAIL_SUBJECT="File changes on $(date +%Y-%m-%d)"
FOLDER_PATH='/home/[username]/public_html'
declare -a IGNORED_FOLDERS=(
  'images/user-cards'
  'images/profile-covers'
);
declare -a IGNORED_FILES=(
  'error_log'
);

# Construct statements to ignore defined folders
for ign_folder in "${IGNORED_FOLDERS[@]}"; do
  statements+=(! -path "*$ign_folder*")
done

# Construct statements to ignore defined files
for ign_file in "${IGNORED_FILES[@]}"; do
  statements+=(! -name "$ign_file")
done

# Prepare email message
message="subject:$EMAIL_SUBJECT\nfrom:$EMAIL_FROM"

echo 'Fecthing changes, this may take a few minutes...'

# Find all changes made in the past 1 day (24h)
# Send results to configured email and any errors to dev/null
# Results printed to terminal (tee) if ran via command line
find "$FOLDER_PATH" -ctime -1 -type f "${statements[@]}" 2> /dev/null | tee >({ echo -e "$message"; cat; } | sendmail $EMAIL_TO)

echo "Email report sent to $EMAIL_TO"
