#! /bin/bash

# Config variable, modify to your needs
EMAIL_TO='recipient@email.com'
EMAIL_FROM='sender@email.com'
EMAIL_SUBJECT="File changes for $(date +%Y-%m-%d)"
FOLDER_PATH='/home/[username]/public_html'
declare -a IGNORED_FOLDERS=(
	'/images/user-cards'
	'/images/profile-covers'
);

# Find all changes made in the past day (24h), send errors to /dev/null
echo 'Fecthing changes, this may take a few minutes.'
files=( $(find $FOLDER_PATH -ctime -1 2> /dev/null) )
echo '=============================================='
