#! /bin/bash

# Config variable, modify to your needs
EMAIL_TO='recipient@email.com'
EMAIL_FROM='sender@email.com'
EMAIL_SUBJECT="File changes for $(date +%Y-%m-%d)"
FOLDER_PATH='/home/[username]/public_html'
declare -a IGNORED_FOLDERS=(
	'/images/user-cards'
	'/images/profile-covers'
);

# Find all changes made in the past day (24h), send errors to /dev/null
echo 'Fecthing changes, this may take a few minutes.'
files=( $(find $FOLDER_PATH -ctime -1 2> /dev/null) )
echo '=============================================='

# Remove file instances that match from ignored folders list
for folder in ${IGNORED_FOLDERS[@]}; do
	# Construct absolute path
	folder="$FOLDER_PATH$folder"
  
  # Escape forward-slashes
  folder=${folder//\//\\\/}

  # Remove ignored folder files with pattern match
  files=( ${files[@]/$folder*/} )
done
